version: '3'
services:
    postgres:
      image: 'postgres:14.5-alpine'
      environment:
        - POSTGRES_PASSWORD =postgres_password
        - POSTGRES_USER=postgres
        - POSTGRES_DB =simple_blog_api
       # - POSTGRES_HOST_AUTH_METHOD=trust
       

    dev:
      depends_on: 
        - postgres
      #build:
       # context: .
        #dockerfile: Dockerfile.dev

      image: axelsilverdew/simple-api:latest
      ports: 
        - '3000:3000'

      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432





      
 